/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var c=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var r=Object.prototype.hasOwnProperty;var g=(e,o)=>{for(var a in o)c(e,a,{get:o[a],enumerable:!0})},I=(e,o,a,l)=>{if(o&&typeof o=="object"||typeof o=="function")for(let n of i(o))!r.call(e,n)&&n!==a&&c(e,n,{get:()=>o[n],enumerable:!(l=t(o,n))||l.enumerable});return e};var h=e=>I(c({},"__esModule",{value:!0}),e);var u={};g(u,{default:()=>d});module.exports=h(u);var s=require("obsidian"),d=class extends s.Plugin{async onload(){this.addRibbonIcon("gear","Lancer CodeIdian",()=>{new s.Notice("Bienvenue dans CodeIdian !")}),console.log("CodeIdian est charg\xE9 \u2705")}onunload(){console.log("CodeIdian est d\xE9charg\xE9 \u274C")}};
