name: Build and Test CodeIdian Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Vérifie le code source du dépôt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Configure Node.js version 16

      - name: Install dependencies
        run: npm install  # Installe les dépendances

      - name: Build the plugin
        run: npm run build  # Compile le projet TypeScript en JavaScript
